spring:
  application:
    name: Team14_BE

  datasource:
    driver-class-name: ${DRIVER_CLASS_NAME}
    username: ${USERNAME}
    url: ${URL}

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
    defer-datasource-initialization: true

  sql:
    init:
      mode: always

logging:
  level:
    org:
      hibernate:
        SQL: debug
        orm:
          jdbc:
            bind: trace

kakao:
  client-id: ${KAKAO_CLIENT_ID}
  redirect-url: ${KAKAO_REDIRECT_URL}

  auth:
    token:
      url: ${KAKAO_AUTH_TOKEN_URL}

  user:
    api:
      url: ${KAKAO_USER_API_URL}

key:
  jwt:
    secret-key: ${JWT_SECRET_KEY}

jwt:
  expire-time: 1
